
[project]
name = "python-fastapi-template"
version = "0.1.0"
description = "A Python project"
authors = [{ name = "Your Name", email = "your.email@example.com" }]
license = "MIT"
dependencies = []

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
